---
# .github/workflows/pages.yml
name: Deploy interactive Bloat Analysis

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write        # needed for deploy-pages
      id-token: write     # needed for configure-pages
    steps:
      - uses: actions/checkout@v4

      - name: Run Neovim bloat & assemble site
        run: |
          # headless bloat → analysis.json
          nvim --headless -u minimal_init.lua +':silent! Bloat $PWD/analysis.json' +qa
          # prepare a public folder
          mkdir -p public/analyze
          cp -R docs/analyze/* public/analyze/
          cp analysis.json public/analyze/metafile.json

      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: public
      - uses: actions/deploy-pages@v1
...
