---
# .github/workflows/pages.yml
name: Deploy Interactive Bloat Analysis

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y neovim nodejs npm
          npm install -g puppeteer

      - name: Run bloat.nvim
        run: |
          nvim --headless -u minimal_init.lua \
            +':silent! Bloat $PWD/analysis.json' \
            +qa

      - name: Clone esbuild Analyze UI
        run: |
          git clone --depth=1 \
            https://github.com/esbuild/esbuild.github.io.git esbuild-ui

      - name: Prepare public folder
        run: |
          mkdir -p public/analyze
          cp -R esbuild-ui/src/analyze/* public/analyze/
          mv analysis.json public/analyze/metafile.json
          # inject the fetch→analyzeMetafile hack if you need it
          sed -i '' \
            's|<input type="file"|<script>fetch("metafile.json")\
               .then(r=>r.json())\
               .then(data=>analyzeMetafile(data,"chartPanel"));\
             </script><input type="file"|' \
            public/analyze/index.html

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - uses: actions/deploy-pages@v4
...
